services:

  db:
    image: postgres:16-alpine
    container_name: employee_db
    restart: always
    environment:
      POSTGRES_DB: GTSPolandHiringDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d GTSPolandHiringDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_api
    restart: always
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=GTSPolandHiringDb;Username=postgres;Password=PostgresPassword123!
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: